name: Deploy MkDocs
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install "mkdocs>=1.6.1,<2.0.0" "mkdocs-material[imaging]>=9.6.15,<10.0.0"
    - run: mkdocs build
    - run: echo "aarish.co" > site/CNAME
    - run: mkdocs gh-deploy --force